### ISSUE TITLE
Sly 2 no-interlacing patch not working

### ISSUE THREAD

**Issue by Jakey757** [PCSX2/pcsx2_patches#12]
Serial: SCUS-97316
CRC: 07652DD9
OSD reports 2 patches are active, automatic de-interlacing sets to none, but the image bobs/shakes/flickers as if nothing changed.
EDIT: Tested patch in software/at native resolution, there is a change in image quality associated with NI patches (vertical resolution halved) but the frame still shakes.

**Comment by icup321** [comment]
This also happens with the Sly 3 no-interlacing patch, but I fixed them by removing one line of code for both of them. I will submit them via a PR later once I've tested them out a bit more.
