### ISSUE TITLE
`SLES-52836_37C182D7.pnach`: is this right?

### ISSUE THREAD

**Issue by israpps** [PCSX2/pcsx2_patches#130]
https://github.com/PCSX2/pcsx2_patches/blob/c6e2dd9c1e20a6b64eb95c5443eb00e922a6ae88/patches/SLES-52836_37C182D7.pnach#L7

I'm talking of the 4 digit value instead of the usual 8 digit

**Comment by refractionpcsx2** [comment]
That should work, sure.

**Comment by refractionpcsx2** [comment]
maybe, if 32bit width is expected.
