### ISSUE TITLE
SLPS-25026_6898435D is probably wrong labeled.

### ISSUE THREAD

**Issue by pgert** [PCSX2/pcsx2_patches#131]
SLPS-25026_6898435D is probably supposed to be SLPM-67546_6898435D.

SLPS-25026 is Dead or Alive 2 (NTSC-J) according to GameDB, PCSX2 WIKI and redump.
https://wiki.pcsx2.net/DOA2:_Hardcore
http://redump.org/disc/19415/

SLPM-67546 is The Lord of the Rings: The Two Towers (NTSC-K) according to GameDB, PCSX2 WIKI and redump.
https://wiki.pcsx2.net/The_Lord_of_the_Rings:_The_Two_Towers
http://redump.org/disc/17466/

**Comment by refractionpcsx2** [comment]
Brilliant patch makers properly adding codes to their patches.

Thanks.
