### ISSUE TITLE
SLES-50677_7DE3F9E8 has the wrong serialcode

### ISSUE THREAD

**Issue by pgert** [PCSX2/pcsx2_patches#134]
SLES-50677_7DE3F9E8 has the wrong serialcode (probably).
The serial is SLES-50822, and the regionalcode is PAL-M3.

DEFA4763 has the serialcode SLES-50677, and the regionalcode PAL-E.

https://forums.pcsx2.net/Thread-No-interlacing-codes?pid=604002#pid604002
https://forums.pcsx2.net/Thread-No-interlacing-codes?pid=603979#pid603979

**Comment by refractionpcsx2** [comment]
according to our forum it's correct

https://forums.pcsx2.net/Thread-Shadow-Hearts-SLES-50677-E--30204?highlight=DEFA4763

it's possible both are the same CRC as they might use the same ELF file, but someone would need to confirm that.

**Comment by pgert** [comment]
Well, I can't find confirmations on the CRC's, only on the serials and region codes:

SLES-50822:
http://redump.org/disc/14055/

SLES-50677:
http://redump.org/disc/51992/

@bositman ?

**Comment by refractionpcsx2** [comment]
I checked in to this and you are right, SLES-50822 has the CRC 7DE3F9E8, SLES-50677 has the CRC DEFA4763
