### ISSUE TITLE
Ratchet and Clank 1 NTSC Widescreen Patch Commented out

### ISSUE THREAD

**Issue by Bubblegum3390** [PCSX2/pcsx2_patches#220]
On current builds of PCSX2 that use the new patches system, the Ratchet 1 widescreen patch does not work because the pnach in the resources zip, every single line is commented out. This was not an issue on cheats_ws builds.
SCUS-97199
CE4933D0

**Comment by refractionpcsx2** [comment]
If somebody fixes the patch, it can be re-enabled.

**Comment by Bubblegum3390** [comment]
I played through the game to 100% completion with the patch on and encountered no issues.

**Comment by refractionpcsx2** [comment]
Then you were very lucky.  It only happens in specific places.
