### ISSUE TITLE
Final Fantasy 7 Dirge of Cerberus WS Patch causes black void in sky

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2_patches#295]
For SLUS-251419 at least, there seems to be problems with the clip plain in the WS patch, which causes a black void to appear in the middle of the screen in the distance. (Also the UI isn't scaled correctly, it's all around a bad patch) 

![image](https://github.com/PCSX2/pcsx2_patches/assets/6278726/3a21309a-d08b-402b-9da3-451476f827e8)

We will disable the patch or now until somebody can fix it.

**Comment by Gabominated** [comment]
I just made a new patch and fixed this rendering issue 
![Dirge of Cerberus - Final Fantasy VII_SLUS-21419_20240128183138](https://github.com/PCSX2/pcsx2_patches/assets/154765720/c63051b3-4e0b-4241-8ade-f7b2446f4ef6)
![Uploading Dirge of Cerberus - Final Fantasy VII_SLUS-21419_20240128174517.png…]()
