### ISSUE TITLE
Invalid Widescreen patch line for Spyro: A Hero's Tail

### ISSUE THREAD

**Issue by Daniel-McCarthy** [PCSX2/pcsx2_patches#303]
### Description:

For "Spyro: A Hero's Tail" [SLUS-20884_94C56923.pnach](https://github.com/PCSX2/pcsx2_patches/blob/main/patches/SLUS-20884_94C56923.pnach#L10) and [SLES-52569_6E51213C.pnach](https://github.com/PCSX2/pcsx2_patches/blob/main/patches/SLES-52569_6E51213C.pnach#L10), the widescreen patches have a broken patch line that will not be loaded due to using `patch=3` which is not a valid option [as per Patch.cpp](https://github.com/PCSX2/pcsx2/blob/master/pcsx2/Patch.cpp#L53).

The behavior is simply that the line gets ignored as if it doesn't exist.
Since the 3 patch lines use this field as a "patch number", they put each line as 1,2,3, so all 3 lines need to be updated to 0, 1, or 2 depending on what is most appropriate for this patch.
```
//Widescreen + Extra Perspective
patch=1,EE,003B28C8,extended,3C013F10
patch=2,EE,003B28DC,extended,3C013F10
patch=3,EE,003B2F08,extended,3C013EC0
```

As I don't have this game, I can't test the impact of the change so am reporting instead of submitting a PR to fix it.

**Comment by Mrlinkwii** [comment]
i managed to test the us version  , with the  `patch=3,EE,003B2F08,extended,3C013EC0 ` removed ,  i saw no difference and nothing broke 
![image](https://github.com/PCSX2/pcsx2_patches/assets/17685135/5ed27d40-6bab-411d-bf08-eb213612a6d8)
