### ISSUE TITLE
Ghostbusters: SLES-55571 does not exist

### ISSUE THREAD

**Issue by PeterDelta** [PCSX2/pcsx2_patches#314]
In the repository there are 3 .pnach that, according to my research, the game with the code SLES-55571 does not exist. If I'm right it can be deleted
http://redump.org/discs/quicksearch/ghostbusters/letter/g/

- SCES-55571_7030A01C.pnach - Verified
- SLUS-21882_7030A01C.pnach - Verified
- SLES-55571_7030A01C.pnach - Incorrect

**Comment by Mrlinkwii** [comment]
hmm i dont think it dose exist , so yeah i think it safe to delete 

the only mention of it is https://forums.pcsx2.net/Thread-Ghostbusters-SLES-55571-E--29583?pid=369628 , which i assume is a typo

**Comment by pgert** [comment]
Perhaps you should make a PR at pcsx2 to have this entry removed from GameIndex.yaml as well.

**Comment by refractionpcsx2** [comment]
PR has been merged. so closing this.

Getting some of our guys to remove it from the gamedb, thanks
