### ISSUE TITLE
REQUEST: Add Technictix and Technic Beat no-interlacing patches

### ISSUE THREAD

**Issue by malikmalikmalikmalikma** [PCSX2/pcsx2_patches#326]
Technic Beat (USA)
```
gametitle=Technic Beat [SLUS-21019]
[No-Interlacing]
author=wakfu[CK]
description=Attempts to disable interlaced offset rendering.
gsinterlacemode=1
//Search pattern: 3829050008004264 (little endian)
//Search mask:    ffffffffffffffff
patch=1,EE,00103684,word,00000000 //64420008
patch=1,EE,001039f4,word,00000000 //64420008
```
[SLUS-21019_34DC8778.zip](https://github.com/PCSX2/pcsx2_patches/files/14386192/SLUS-21019_34DC8778.zip)

Technictix (JP)
```
gametitle=Technictix [SLPS-20055]
[No-Interlacing]
author=pcsx2user156
description=Attempts to disable interlaced offset rendering.
gsinterlacemode=1
patch=1,EE,00102FFC,word,00000000
patch=1,EE,0010336C,word,00000000
```
[SLPS-20055_59D0C07E.zip](https://github.com/PCSX2/pcsx2_patches/files/14389564/SLPS-20055_59D0C07E.zip)

**Comment by pgert** [comment]
author of the hack for SLPS-20055_59D0C07E is pcsx2user156
https://forums.pcsx2.net/Thread-No-interlacing-codes?pid=632814#pid632814

**Comment by malikmalikmalikmalikma** [comment]
> author of the hack for SLPS-20055_59D0C07E is pcsx2user156 https://forums.pcsx2.net/Thread-No-interlacing-codes?pid=632814#pid632814

thanks! I'll add him as the author
