### ISSUE TITLE
REQUEST: Add Shin Megami Tensei III: Nocturne no-interlacing patches and FMV fix and Widescreen fix

### ISSUE THREAD

**Issue by Christian7600000** [PCSX2/pcsx2_patches#327]
Shin Megami Tensei III: Nocturne (Japan)
SLPM-65242 9F724384

**Comment by pgert** [comment]
Requests like this are better done in the forum.
https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches
https://forums.pcsx2.net/Thread-No-interlacing-codes
https://forums.pcsx2.net/Thread-60-fps-codes
