### ISSUE TITLE
Dynasty Warriors 5: Xtreme Legends crashing during a cutscene due to the Widescreen Patch

### ISSUE THREAD

**Issue by bizarf** [PCSX2/pcsx2_patches#335]
This crash will always happen on the map, Conquest of Nan Zhong for the Shu side. It happens when you take the base next to the poison swamp in the middle of the map, as a cutscene plays. This is unavoidable as that cutscene will play if that specific base falls due to someone else from Shu taking it. I was able to get around this crash by turning off the widescreen patch. 

To play this map, you have to use the disc swapping feature to load the original data and then it can be selected in Free Mode or be encountered in a Shu character's Musou mode (Zhuge Liang, Huang Zhong, ect). 

This might affect Dynasty Warriors 5 as well, but haven't checked as I don't have the stage unlocked. 

I'm using the latest nightly build.

**Comment by pgert** [comment]
CRC and serial-code of the disc?

**Comment by bizarf** [comment]
I'm sorry about that. I knew I forgot something. It's SLUS-21299. The CRC is A719D130

**Comment by bizarf** [comment]
I just checked Conquest of Nan Zhong (Shu) in Dynasty Warriors 5 (SLUS-21153, CRC:6677B437) and the cutscene plays without any crash, so this crash is only in Xtreme Legends.

**Comment by pgert** [comment]
The hack needs a cutsceen zoom fix, and should be disabled until someone fixes it.
https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=640678#pid640678

**Comment by pgert** [comment]
drobovik at the forums claims to have a working hack.
https://forums.pcsx2.net/Thread-Dynasty-warriors-5XL-crashes-in-spesific-ingame-cutscene?pid=641101#pid641101

**Comment by bizarf** [comment]
> drobovik at the forums claims to have a working hack. https://forums.pcsx2.net/Thread-Dynasty-warriors-5XL-crashes-in-spesific-ingame-cutscene?pid=641101#pid641101

I just tested the fix and it works! 

I added "patch=1,EE,00146ac4,word,3c023e10" at the end of the widescreen code in the patches file for this game. 

I'll close this issue now, but I haven't tested the other stages listed in the comments as I wasn't aware those stages had issues as well.
