### ISSUE TITLE
Harry Potter and the Chamber of Secrets German Version Patches disabled when you use Retroachievements (Hardcore Mode)!

### ISSUE THREAD

**Issue by Snake356** [PCSX2/pcsx2_patches#357]
Hey guys, is it possible that you can implement the patch for the German version so that the patch is no longer deactivated for Hardcore Mode Retroachievements?

Here are the codes for the German version:

gametitle=Harry Potter und die Kammer des Schreckens (PAL-G) [SLES-51194] CRC: C5473413

[Widescreen 16:9]
gsaspectratio=16:9
author=Arapapa
comment=Widescreen Hack
//Widescreen hack 16:9
//Zoom
patch=1,EE,004ca798,word,3c013f24 //3c013f49
patch=1,EE,004ca79c,word,34210000 //34210fda
//Y-Fov
patch=1,EE,004e8eb0,word,3c013fe3 //3c013faa
patch=1,EE,004e8eb4,word,34218e2a //3421aaab
//Button fix
//patch=1,EE,0031cb24,word,3c013fd0 //3c013f9c
//patch=1,EE,0031cb28,word,342197af //342171c7
//Font Y-Fov
//patch=1,EE,20541894,extended,3B0882F1 //3acccccd
//Font Y-Position
//patch=1,EE,205418b4,extended,bf000000 //bec00000
//Font Zoom
//patch=1,EE,205418bc,extended,3faaaaab //3f800000
//Widen HUD to hide icons
//patch=1,EE,205E9F30,extended,3F95C28F
// Commented out as it broke loading screen font and other stuff.

[50 FPS]
author=asasega
comment=Unlocked at 50 FPS. Might need enable EE Overclock to be stable.
patch=1,EE,00544168,word,00000001

I have always played with the codes with the German version and have not experienced any problems.

Is it possible to fix this?

**Comment by refractionpcsx2** [comment]
I don't think the hang fixes are needed anymore, can we remove them please? Thanks.

**Comment by Snake356** [comment]
Yes, you can certainly remove them, of course I didn't know that.
