### ISSUE TITLE
Auto Modelista Modem Pack Widescreen Request

### ISSUE THREAD

**Issue by ultrabub575** [PCSX2/pcsx2_patches#369]
I Need A Widescreen Patch For SLPM-65183.

**Comment by pgert** [comment]
Post such requests in the forum.
https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches

**Comment by ultrabub575** [comment]
> Post such requests in the forum. https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches

Okay. Thanks!
