### ISSUE TITLE
Crash Nitro Kart SLES-51511 480p patch

### ISSUE THREAD

**Issue by PeterDelta** [PCSX2/pcsx2_patches#390]
This is the patch published. Example in hell islands

[480p Mode]
gsinterlacemode=1
patch=1,EE,00446A74,word,24110000
patch=1,EE,00446A78,word,24120050
patch=1,EE,00446A84,word,24130001
patch=1,EE,0058BF7C,word,3C023EE8
![Crash Nitro Kart_SLES-51511_20240713171243](https://github.com/user-attachments/assets/83915c9e-6fc4-4690-a54c-4d6866276a43)

This is image original at 50hz
![Crash Nitro Kart_SLES-51511_50hz](https://github.com/user-attachments/assets/f3f6b015-791e-4a05-934a-7d844b6c4725)

Without the last line
![Crash Nitro Kart_SLES-51511_sin linea](https://github.com/user-attachments/assets/ce9039d9-2e4e-4503-8a8c-f1bbc63bec60)

As it is, moving the image a little up would match the 50 Hz one, the only thing the hud would be a little bigger but I think it would be the least important.

**Comment by CRASHARKI** [comment]
That is not what 50hz really looks like, make sure you have Show Overscan activated in Graphics Settings of PCSX2. What you are seeing is the game without the Overscan option, which means the resolutions is not really changing, which means the patch is perfect without the last line. Also, I don't know why this game doesn't have the show overscan option forced on the PCSX2 database, that's another issue.

**Comment by CRASHARKI** [comment]
You have the 480p patch on, it only makes a difference with it deactivated.
