### ISSUE TITLE
Need for Speed Underground (SLUS-20811) Widescreen Patch Possibly Not Working

### ISSUE THREAD

**Issue by sinisterseed** [PCSX2/pcsx2_patches#395]
Put a "possibly" there because honestly I'm not entirely sure myself, unlike I was with HP2.

But the WS patch does not actually seem to do much, if anything. If I switch to 4:3 and then back to 16:9, the game just stretches out, and none of the UI elements seem to adapt to the new format either.

Back in Hot Pursuit 2, that patch seemed to at least affect the menus. But here, I'm not seeing anything. I tried reloading the patches, checking and unchecking the patch in the Game Properties window while the game is running, and reloading the patch seems to make no difference at all. The 60fps patch does work correctly, but not the WS one.

How the game looks like on my end. The UI in particular is very stretched:

![Need for Speed - Underground_SLUS-20811_20240720183800](https://github.com/user-attachments/assets/f0badb21-49ea-4bc7-96ad-022b43386c61)

**Comment by sinisterseed** [comment]
Fair enough, I suspected the HUD might be something that we'll have to leave as-is, if it can't be properly adapted.

But it's the game side of things where I can't wrap my head around. If I switch to 4:3 then 16:9, I can see that the game visibly stretches out, which is why I'm not sure the patch is actually working, but I'm also not convinced as HP2 was a more noticeable case last time, which was also the reverse of this - UI was properly adapted, gameplay was stretched.

**Comment by sinisterseed** [comment]
No, this does seem to look different from what I see. The 16:9 one has the HUD stretched out, but the cars and the world look the same otherwise.

For me, switching between modes makes a noticeable difference. Could it be that the patch was meant for the PAL version instead? That could explain why the patch does not seem to make any difference for me.

I'll try getting my hands on the PAL version to see if I can confirm as the patch just not working for the NTSC version.

**Comment by sinisterseed** [comment]
I just did some more testing, and now it gets even weirder. I'm still suspecting that the WS patch is not working, and I found something else that might connect this.

What I did was run the game, and disable WS patches both globally and in the game's properties, to ensure nothing is getting enabled. Then I did my usual run, switching to 4:3 and back to 16:9 with them disabled. What I discovered, is that 16:9 actually seems to have the stretched look the with or without the patches enabled, I can not actually spot any difference in 16:9 without patches, and 16:9 with the patches enabled during racing.

I don't know what to think anymore, but this seems to confirm the patches do in fact do nothing, if there is no difference with them disabled or enabled in 16:9. Can you spot any differences if you follow the same procedure?

**Comment by sinisterseed** [comment]
Made some screens just as you were typing I guess, lol.

So here's my comparison:

Patches globally disabled in 16:9 mode:

![Need for Speed - Underground_SLES-51967_20240720231258](https://github.com/user-attachments/assets/2a26095b-2d24-4cc6-8841-bfd2ca1e3cbb)

Patches enabled also in 16:9 AND "Auto" mode (seems Auto enforces 16:9 if WS patches are enabled):

![Need for Speed - Underground_SLES-51967_20240720231346](https://github.com/user-attachments/assets/0e341f0d-74a9-4668-9269-666aa5a0e501)

As you can see, there is no difference between the two at all. So at this point I can only draw one conclusion - either I'm being very stupid and missing something obvious, or the patches do, in fact, achieve nothing, as 16:9 mode looks the same regardless of whether the patches are enabled or not.

I also played UG2 a while ago as well, and while that one had a built-in WS mode, it did not look as stretched as UG1 does.

**Comment by sinisterseed** [comment]
> The one you left aside that narrows you probably have the 4:3 pcsx2 option enabled and the patch enabled. Try taking a capture without patches and in 4:3 you will see the difference. Tell me what proof is that you show? I'll do the comparison with mine to see if the same thing happens to me.

No, it isn't. The 4:3 one has the WS patches disabled globally, and I also disabled them from the game's properties tab just to be sure.

As for how I did the comparisons, I've already explained how. First one was with the WS patches enabled globally (under PCSX2's Settings - Graphics tab), and the other is with it disabled, as well as ensuring they're disabled from the game's properties tab (right-click on the game's etry in the library - Properties - Patches, and make sure the WS patch is disabled). That should give you the same results.

The patches don't feel right like this. Tunnels, especially in Drag races, feel weirdly claustrophobic, as the ceiling appears too low. I've been playing the PC versions of those games for a long time too, using ThirteenAG's widely popular WS fixes, and the results in PCSX2 with these patches don't feel correct when using those as reference either.

**Comment by sinisterseed** [comment]
> If you do everything right there is a possibility that it could fail but I would be surprised. What is the name of that test you show?

I wouldn't at this point, unless something broke in PCSX2 recently, but I doubt it since that doesn't explain why it would affect only Underground. None of my other games exhibit such peculiar behavior. Again, for comparison, note that Underground 2 has a built-in WS mode, and the results when using it feel a lot better than this. If you have it you can probably check it out. 

The 4:3 image you said looked too tall should be correct (if it was from the WS fixes I would expect the HUD elements to turn slightly oval from excessive tallness). Tunnels in particular feel just right, if the image was too tall it would give the opposite impression, that the walls are squeezing you in while traversing, whereas with those patches the ceilings do, indicating that the image is likely squished vertically.

**Comment by sinisterseed** [comment]
I'm completely clueless myself as well. This has never happened before to me, and it's also not like I messed with PCSX2's settings a lot to break something. My settings are largely default, with the sole exception of resolution (3x Native), 16x Anisotropic Filtering, and enabling WS and No-Interlacing patches globally. That's it, everything else is default. And I'm using the latest master of the patches, I periodically delete and redownload the patches folder once too many changes pile up to be sure I'm up to date, and not overwriting the existing folder for best results.

**Comment by sinisterseed** [comment]
Well, actually scratch this. Deleted my previous comment.

Today I decided to just do a global reset of PCSX2's configuration and see what happens. Now with a fresh start, either whatever was wrong went away, or it was always placebo due to being so used to how the PC version looks like with ThirteenAG's WS Fix.

Whatever happened here, at least went away (assuming it was there to begin with, and I wasn't just imagining things, lol). Closing this now.

**Comment by sinisterseed** [comment]
> You may be right, the US version seems incomplete and the PAL is missing things. I have fixed everything, the FMV at the beginning and the trailers were cut out, the reflections and lights of some streetlights were misaligned. Now it works as it should, I started a new game and so far I don't see any errors. Download it and just change the pnach name to your region name SLUS-20811_CB99CD12 and tell me if you see any errors.
> 
> https://github.com/PeterDelta/PCSX2/blob/2/patches/SLES-51967_FDA10318.pnach

Oh hey, looks like we did get something productive out of this in the end. I just finished checking the patch, and it does seem to make quite an improvement overall.

However, for the stretching thing, since this is so confusing, what I decided to do, is actually compare how other emulators handle WS in Underground. And what better point of reference, than Dolphin?

Since I had that port for ages but forgot about it, that's exactly what I did. This is how the GC version looks in 16:9 with the WS Gecko code from their wiki.

![GNDE69_2024-07-21_17-49-11](https://github.com/user-attachments/assets/70692df0-46be-42c6-96d0-1e4c0489ebef)

There is still a little bit of stretching when switching to 16:9, but it's not as pronounced as in my older screens by far. The UI also seems to adapt to 16:9 mode much better.

**Comment by sinisterseed** [comment]
> The first impression I get is that it looks very narrow. I don't know what resolution it handles in gamecube but the comparison has to be done with the same game, that is, you have to compare it with the original 4:3 image without a patch or tricks. You cannot compare one patch with another. If not, when applying the patch on the PS2 I wouldn't fit the perspective

I know, but I think we have just about enough screenshots in this topic as it is, hence why I didn't add a 4:3 screenshot in Dolphin and limited it to just the WS fix.

So I resorted to just describing the effect, which in this case, is just enlarging the field of vision to the sides of the screen. There's almost no stretching involved in the process at all unlike what we're seeing in PCSX2.

**Comment by rraihansaputra** [comment]
Sorry for bumping this issue, I'm unsure if I should create a new issue or not, but the current patch shipped with PCSX2 doesn't work with my Underground ISO with the same CRC:

Serial: SLUS-20811
CRC: CB99CD12

I was confused as the previous screenshots show, but got a tip from reddit (/u/astroturf007) for these values:

```
patch=1,EE,004ff434,word,3F24A9CF
patch=1,EE,004ff628,word,3f470000
patch=1,EE,004ff630,word,3f470000
```

https://old.reddit.com/r/PCSX2/comments/1oehcnz/widescreen_patch_not_working_nfs_underground/nl1qpl3/

and it just worked for me (fresh .pnach with just those 3 lines, the in-pcsx2 patch disabled). Similar as the fixed screenshots PeterDelta gave (cars don't look stretched, more horizontal fov).

For more info:
- i'm on beta PCSX2 v2.7.264
- i'm playing on macOS on Metal renderer

I'm thinking of updating the .pnach, but seems like there's reason to be careful here.

**Comment by sinisterseed** [comment]
Very interesting development.

I've not checked the PS2 version of Underground since last year, despite it gathering "dust" on my drive, but if this problem has since resurfaced, it might be worth re-investigating the issue and updating the patch, especially if the above values work for that version of the game. 

In my opinion, at least. I'm now having flashbacks to how confusing the whole mess was last time we went down the rabbit hole and being unable to figure out why my screenshots looked stretched, unlike PeterDelta's, lol.
