### ISSUE TITLE
CID the Dummy (U)(SLUS-21754) patch creates branch in branch delay slot.

### ISSUE THREAD

**Issue by Goatman13** [PCSX2/pcsx2_patches#406]
With current version of pcsx2 (v2.1.105) it skips next jal at all as far as i know. Beside that patch seems to not work at all. 
![image](https://github.com/user-attachments/assets/4cdf9a45-50ab-4131-8756-06ba7dd15e4d)

Log:

[   76.2693] OSD [LoadPatches]: 1 game patches are active.
[   76.2697] Applying settings...
[   76.2703] Patch: Setting aspect ratio to 16:9 by patch request.
[   76.2709] Updating GS configuration...
[   76.2794] Branch c09317a in delay slot!
[   78.1483] Branch c09317a in delay slot!

**Comment by Mrlinkwii** [comment]
if it dosent work id say disable it

**Comment by Goatman13** [comment]
Ah, ok. I didn't know that. Indeed, patch is working. There is still issue with delay slot, instruction at 0x228AA4 will be skipped at all. In this case it will skip whole function. I will edit my pr.
