### ISSUE TITLE
MGS 3 Subsistence: Disable ws for problem?

### ISSUE THREAD

**Issue by PeterDelta** [PCSX2/pcsx2_patches#429]
https://github.com/PCSX2/pcsx2_patches/pull/428
Where has the error been seen in MGS3 subsistence? I finished it from start to finish a few months ago, and I was correcting it on the fly without any problem... and the ShizCalev himself confirms it.
If any anomaly has been detected, where is it located? In order to correct it, I would fix it in a moment.

**Comment by ShizCalev** [comment]
I'm pretty sure it was erroneously disabled since no reports were linked other than #417
