### ISSUE TITLE
Ico (PAL) no-interlacing and other misc. patches

### ISSUE THREAD

**Issue by DrAzathoth** [PCSX2/pcsx2_patches#433]
**No-Interlacing**

[No-Interlacing]
author=Red-tv
gsinterlacemode=1
//No-Interlacing
patch=1,EE,0013CAD0,word,30420000
patch=1,EE,001144AC,word,30420000

**21:9 Ultrawide**

[21:9]
author=Devina
//21:9
patch=1,EE,20114dd0,extended,3c013f10
patch=1,EE,20114dd4,extended,4481c000
patch=1,EE,20114de0,extended,46181082
patch=1,EE,201146f4,extended,24030aaa
patch=1,EE,2054e478,extended,44fa0000

**60 FPS patches**

[60 FPS]
description=Might need to enable 130% or 180% EE Overclock to be stable. Makes some animations run too fast.
//true 60fps
patch=1,EE,E0010000,extended,0063AA08
patch=1,EE,0028F4C4,extended,00000001

[30 FPS Cutscenes]
description=Force cutscenes to run at 30 FPS (they run at double speed if forced to 60).
//Revert to 30 fps every time there is a Cutscenes
patch=1,EE,E0010001,extended,0063AA08
patch=1,EE,0028F4C4,extended,00000002

**Disable Motion Blur**

[Disable Motion Blur]
patch=1,EE,001fca60,word,03e00008
patch=1,EE,001fca64,word,00000000

**Debug Menu**

[Debug Menu]
description=Press select to open the Debug Menu.
patch=1,EE,20101F94,word,0C06C966
patch=1,EE,201AF850,word,0806BD28

**Comment by pgert** [comment]
Issue addressed in #434.
