### ISSUE TITLE
Bloody Roar 3 (Japan) (v2.01) no interlacing patch causes the game to hang with a black screen

### ISSUE THREAD

**Issue by crashGG** [PCSX2/pcsx2_patches#439]
SLPM-62055_64328775.pnach no interlacing patch for Bloody Roar 3 (Japan) (v2.01) (Follow redump naming)  causes the game to hang with a black screen

**Comment by pgert** [comment]
Can you find out if it is "Progressive mode + No interlacing" or "Null Int Ints." that causes the hang, and if both hacks are needed?

**Comment by crashGG** [comment]
After my simple test, "Progressive mode + No interlacing" part has the problem, delete this part,and keep "Null Int Ints." part alone can make the Progressive mode work fine.
