### ISSUE TITLE
[SLUS-20362] NFS: Hot Pursuit 2 - "HUD fixed for widescreen" patches doesn't work / is not needed

### ISSUE THREAD

**Issue by Foul-Tarnished** [PCSX2/pcsx2_patches#441]
The patch "HUD fixed for widescreen" doesn't fix the UI for widescreen, and actually the "widescreen 16:9" patch fix the UI already by itself.
So using the widescreen 16:9 patch alone is the best:

Widescreen 16:9 only:
![Image](https://github.com/user-attachments/assets/37ff3f04-a5a8-40a1-a8c8-114ad907fa2a)

Widescreen 16:9 + HUD fix for widescreen:
![Image](https://github.com/user-attachments/assets/aadded83-eccb-4927-a287-ba95b74ca4ae)

So I believe it's best to remove this patch altogether and let users use the "Widescreen 16:9" patch alone.
Sure, the text and UI might look a bit stretched, but the UI being on the outer part of the screen is way more useful (to not have the view cluttered)

Also, the "HUD fix" revert all menus to 4:3, and make some specific scenes buggy:
![Image](https://github.com/user-attachments/assets/5f077c61-ac30-4e68-b89a-8c386a8729b1)

**Comment by Foul-Tarnished** [comment]
As I said, yeah the UI is stretched without the hack

The main issue i find with it, is the UI is not being put to the exterior
sides, it's even more on the middle of the screen...

**Comment by crashGG** [comment]
In my opinion, the widescreen  + hud fix makes the speed dial return to a round shape. It is closer to the original state of the game, which should be a step further than the disproportionate stretching of the HUD UI.

**Comment by JordanTheToaster** [comment]
Closing as you misunderstand what the 16:9 HUD cheat does.
