### ISSUE TITLE
Need for Speed Hot Pursuit 2 (SLUS-20362) WS patch doesn't seem to be working correctly

### ISSUE THREAD

**Issue by sinisterseed** [PCSX2/pcsx2_patches#56]
Although the message that "3 widescreen patches are active" appears in the top-left corner when booting the game, the WS patch doesn't seem to be doing its job during the actual gameplay.

The game maintains a stretched appearance when running in 16:9. I tried switching back to 4:3 to ensure that it's not my eyes deceiving me, and 16:9 definitely doesn't look correct.

This is what I'm seeing:

![gfdgdd](https://user-images.githubusercontent.com/57503728/228015570-11f2d460-a433-4f82-be84-350318d517f0.png)

**Comment by refractionpcsx2** [comment]
It does look stretched, you will need to ask the original author to correct the patch, as it evidently does very little.  Not something we can action on our end.
