### ISSUE TITLE
[BUG] Problem with Crash Tag Team Racing WS Patch

### ISSUE THREAD

**Issue by kamfretoz** [PCSX2/pcsx2_patches#60]
Serial: SLUS-21191
CRC: AA525269

Notice the water splashes in the waterfall on the back and the light bloom effect on the floating yellow key above some of the characters. i feel like their position are relative to where the camera is currently looking at. **Tested by disabling the WS patch and it fixes the issue.**

Here is the video preview:
https://cdn.discordapp.com/attachments/923492653788692480/1076870735634649209/Crash_Tag_Team_Racing_SLUS-21191_20230219211459.mp4

**Comment by refractionpcsx2** [comment]
Would you consider this gamebreaking? If so we can disable it. If not you will need to inform the original patch author to fix it, we just distribute them.
