### ISSUE TITLE
Dragon Ball Z Budokai 3 widescreen patch disengages when choosing battle again or continue

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2_patches#62]
Most easily reproducible when going into dual mode, but can also be triggered in dragon universe mode or possibly other ways. Basically the widescreen hack works fine initially but when you lose a battle and hit continue or battle again the widescreen patch disengages and everything becomes stretched. Characters look like Big Chungus Going back to the main menu or character select screen re activates the patch. 

Before losing a battle and selecting battle again
![Screenshot (93)](https://user-images.githubusercontent.com/12180630/230685414-a368883f-8c56-4386-8068-2a2b4e12842a.png)

After losing a battle and selecting battle again. 
![Screenshot (94)](https://user-images.githubusercontent.com/12180630/230685561-70a07c41-fa3b-46a0-ba69-ffdf3d2ad103.png)

See the similarities
![avatars-8MhWPFNHR9kIZjjV-v6AhSA-t500x500](https://user-images.githubusercontent.com/12180630/230685695-a2b9433d-4d65-4b58-a8ab-c45b1b615e8c.jpg)

**Comment by refractionpcsx2** [comment]
We don't create the patches, you will need to ask whoever original made the patch to fix it.

If you consider this gamebreaking we can disable the patch, otherwise there's not much we can do here.

**Comment by BParks21** [comment]
Who made it?

**Comment by refractionpcsx2** [comment]
no idea, probably somebody on the forum, I would start there anyways https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches

**Comment by BParks21** [comment]
Idk I'll try to figure out who made it. I would just disable it for now tbh. Doesn't work right.

**Comment by refractionpcsx2** [comment]
okay, do you know what the CRC is for that game?

**Comment by BParks21** [comment]
2A4B60EB

**Comment by ke5koB** [comment]
Fixed patch
DragonBall Z Budokai 3 SLUS-20998
[2A4B60EB.zip](https://github.com/PCSX2/pcsx2_patches/files/11643560/2A4B60EB.zip)

**Comment by BParks21** [comment]
Will this patch be included in a future pcsx2 update?

**Comment by ke5koB** [comment]
If you check it out and confirm that it works, then probably the PCSX2 devs will add it in future updates

**Comment by BParks21** [comment]
Seems to work fine now.
