### ISSUE TITLE
WS patch of Tom Clancy's Ghost Recon 2 (US) 

### ISSUE THREAD

**Issue by Mrlinkwii** [PCSX2/pcsx2_patches#64]
the WS patch for Tom Clancy's Ghost Recon 2 (US)  was causing issues with loading  ( it disabled for the  moment #63 ) ,. it would be nice if it could be fixed up to work

**Comment by refractionpcsx2** [comment]
The creator on the forum would need to be notified, we don't fix the patches, we just supply them with the emulator.
