### ISSUE TITLE
SLUS-20661 Fairly Odd Parents Breakin' Da Rules WS Hack doesn't work properly

### ISSUE THREAD

**Issue by PsychoticFox** [PCSX2/pcsx2_patches#65]
The 16:9 widescreen hack loads fine, and in the menu it looks correct, but ingame, the aspect ratio is incorrect and somewhat squished. 
![bandicam 2023-04-09 15-36-19-720](https://user-images.githubusercontent.com/69675052/230797812-c19364c5-a600-4c92-b922-b740159202c5.jpg)

What the game and models are supposed to look like (minus the black bars of course)
![bandicam 2023-04-09 15-37-58-789](https://user-images.githubusercontent.com/69675052/230797850-4a47d1d5-13fe-4986-b9cc-94ccce9d2906.jpg)

**Comment by refractionpcsx2** [comment]
would you consider this gamebreaking? If not you need to ask on the forums or whomever made the patch.

**Comment by lightningterror** [comment]
Closing, author or someone willing should check the patch.
