### ISSUE TITLE
Shadow Hearts [SLUS-20347] widescreen patch does not work correctly.

### ISSUE THREAD

**Issue by BlueGrassBlade** [PCSX2/pcsx2_patches#7]
After loading the game with widescreen patches enabled (PCSX2 Nightly - v1.7.3532), the game displays that patches are loaded but the aspect ratio is not right. See screenshots for an example.

Wrongly displayed with widescreen enabled and loaded.
![shadowhearts1-widescreen_wrong](https://user-images.githubusercontent.com/79953477/200210658-523805d6-32b5-47a6-aa9b-4ee1afcd6b12.png)

Correct look.
![shadowhearts1-normal](https://user-images.githubusercontent.com/79953477/200210683-9200141b-6edd-470b-97f6-fce3e0322d2f.png)

**Comment by refractionpcsx2** [comment]
huh so the patch just doesn't do anything :/

**Comment by ke5koB** [comment]
Game uses prerendered 2d backgrounds,so patch affects only battles and menus.

**Comment by refractionpcsx2** [comment]
okay, well if you have concerns with the patch not doing everything you hoped, you need to speak to the author of the patch, we don't make them, we only distribute them.
