### ISSUE TITLE
Capcom vs. SNK 2 - Mark of the Millennium 2001 (SLUS-20246) WS Patch causes the image to be shifted to the right

### ISSUE THREAD

**Issue by sinisterseed** [PCSX2/pcsx2_patches#70]
Essentially the title. Enabling the WS patch (and no-interlacing patches, for that matter) in this game causes the image to shift to the right of the screen for some reason.

I have tried running the game in the regular 4:3 format with the patches disabled, and it works as intended. In 16:9 with the patches enabled, however, that's a different story. It happens everywhere, both in the menus and during gameplay - and during gameplay it makes it impossible to see what's on the right edge of the screen, as it goes beyond the border.

![gdfggd](https://github.com/PCSX2/pcsx2_patches/assets/57503728/ffa5dfb9-4ee2-4ac2-8c0b-a36899ecde4d)

**Comment by refractionpcsx2** [comment]
We can disable the patch, we can't fix it though, that's down to the community or whoever wrote it.

**Comment by refractionpcsx2** [comment]
Patch has been disabled
