### ISSUE TITLE
Wrong serials/filenames

### ISSUE THREAD

**Issue by pgert** [PCSX2/pcsx2_patches#92]
According to Gabominated at the forum:

5B9ACF79: SLES-51110 & PAL-S - not SLES-51109 & PAL-G.
gametitle=Hitman 2 - Silent Assassin * PAL-S * SLES-51110 * 5B9ACF79

72DC82B5: SLES-53032 & PAL-S - not SLES-53030 & PAL-G.
gametitle=Hitman - Blood Money * PAL-S * SLES-53032 * 72DC82B5

**Comment by refractionpcsx2** [comment]
As I suspected, most versions had the same CRC, just different serials, so I've duplicated and updated accordingly.
