### ISSUE TITLE
Ratchet & Clank: Up Your Arsenal 16:9 Widescreen patch isn't working for Multiplayer

### ISSUE THREAD

**Issue by isaac-lal** [PCSX2/pcsx2_patches#93]
Patch file: SCUS-97353_45FE0CC4.pnach 

PCSX2 Version: 1.7.4595

16:9 Widescreen patch for Ratchet & Clank: Up Your Arsenal isn't working for multiplayer. The patch works perfectly fine for Singleplayer however, but when the multiplayer screen is hit, there is a "No patches are found/enabled" notification. The thing is that the patch was working perfectly fine in multiplayer in the earlier builds up until last week.

**Comment by refractionpcsx2** [comment]
As I explained on Discord, you will need to find out what the ELF is called and the CRC for it so we can duplicate the patch, otherwise we can't do anything about it.
